name: Build Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Initialize Go module
        run: go mod init

      - name: Run Go tests
        run: go test ./backend/...

      - name: Build and run
        run: |
          docker-compose up -d

        run: go test ./...

      - name: Build and run
        run: |
          docker-compose up -d
