name: Build and Test App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Run Unit Tests
      working-directory: backend
      run: go test ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and run 
      run: docker-compose up -d
  
  publish-docker-image:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
  
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Tag and push Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/final_ing_3_backend_1:latest ./backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/final_ing_3_frontend_1:latest ./frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/final_ing_3_mysql-container_1:latest ./db
          
          docker push ${{ secrets.DOCKER_USERNAME }}/final_ing_3_backend_1:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/final_ing_3_frontend_1:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/final_ing_3_mysql-container_1:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
